### ISSUE TITLE
SeriDeseri.deserialize; Could not deserialize

### ISSUE THREAD

**Issue by georgeOsdDev** [georgeOsdDev/xitrum-leochat#11]
```
[DEBUG] Could not deserialize: Array(1, 0, 108, 101, 11 .....
com.twitter.bijection.InversionFailure: Failed to invert: [B@bf38f5d
        at com.twitter.bijection.InversionFailure$$anonfun$partialFailure$1.applyOrElse(InversionFailure.scala:43) ~[bijection-core_2.10-0.5.2.jar:na]
        at com.twitter.bijection.InversionFailure$$anonfun$partialFailure$1.applyOrElse(InversionFailure.scala:42) ~[bijection-core_2.10-0.5.2.jar:na]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.3.jar:0.13.0]
        at scala.util.Failure.recoverWith(Try.scala:172) ~[scala-library-2.10.3.jar:0.13.0]
        at com.twitter.bijection.Inversion$.attempt(Inversion.scala:30) ~[bijection-core_2.10-0.5.2.jar:na]
        at com.twitter.chill.KryoInjection$.invert(KryoInjection.scala:29) ~[chill-bijection_2.10-0.3.4.jar:0.3.4]
        at xitrum.util.SeriDeseri$.deserialize(SeriDeseri.scala:13) ~[xitrum_2.10-2.10.jar:2.10]
        at leochat.model.LeoFS$.read(Leofs.scala:131) [classes/:na]
        at leochat.model.LeoFS$.readAndPrev(Leofs.scala:147) [classes/:na]
        at leochat.model.LeoFS$.readWithMarker(Leofs.scala:165) [classes/:na]
        at leochat.action.LeoChatRest.execute(Chat.scala:69) [classes/:na]
        at xitrum.action.Filter$$anonfun$1.apply$mcV$sp(Filter.scala:41) [xitrum_2.10-2.10.jar:2.10]
        at xitrum.action.Filter$class.callExecuteWrappedInAroundFilters(Filter.scala:45) [xitrum_2.10-2.10.jar:2.10]
        at leochat.action.LeoChatRest.callExecuteWrappedInAroundFilters(Chat.scala:66) [classes/:na]
        at xitrum.Action$class.xitrum$Action$$callExecuteWrappedInAroundFiltersThenAfterFilters(Action.scala:160) [xitrum_2.10-2.10.jar:2.10]
        at xitrum.Action$$anonfun$dispatchWithFailsafe$2.apply$mcV$sp(Action.scala:79) [xitrum_2.10-2.10.jar:2.10]
        at xitrum.Action$class.tryCache(Action.scala:149) [xitrum_2.10-2.10.jar:2.10]
        at xitrum.Action$class.dispatchWithFailsafe(Action.scala:79) [xitrum_2.10-2.10.jar:2.10]
        at leochat.action.LeoChatRest.dispatchWithFailsafe(Chat.scala:66) [classes/:na]
        at xitrum.handler.up.Dispatcher$.dispatch(Dispatcher.scala:32) [xitrum_2.10-2.10.jar:2.10]
        at xitrum.handler.up.Dispatcher.messageReceived(Dispatcher.scala:63) [xitrum_2.10-2.10.jar:2.10]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.7.0.Final.jar:na]
        at xitrum.handler.up.MethodOverrider.messageReceived(MethodOverrider.scala:54) [xitrum_2.10-2.10.jar:2.10]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.7.0.Final.jar:na]
        at xitrum.handler.up.BodyParser.messageReceived(BodyParser.scala:52) [xitrum_2.10-2.10.jar:2.10]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.7.0.Final.jar:na]
        at xitrum.handler.up.UriParser.messageReceived(UriParser.scala:40) [xitrum_2.10-2.10.jar:2.10]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:281) [netty-3.7.0.Final.jar:na]
        at xitrum.handler.up.Request2Env.messageReceived(Request2Env.scala:29) [xitrum_2.10-2.10.jar:2.10]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.7.0.Final.jar:na]
        at xitrum.handler.up.PublicResourceServer.messageReceived(PublicResourceServer.scala:38) [xitrum_2.10-2.10.jar:2.10]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.7.0.Final.jar:na]
        at xitrum.handler.up.PublicFileServer.messageReceived(PublicFileServer.scala:39) [xitrum_2.10-2.10.jar:2.10]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.7.0.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.7.0.Final.jar:na]

...

Caused by: com.esotericsoftware.kryo.KryoException: Buffer underflow.
Serialization trace:
body (leochat.model.Msg)
        at com.esotericsoftware.kryo.io.Input.require(Input.java:156) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.io.Input.readUtf8_slow(Input.java:524) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.io.Input.readUtf8(Input.java:517) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.io.Input.readString(Input.java:447) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:157) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.read(DefaultSerializers.java:146) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:699) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:611) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729) ~[kryo-2.21.jar:na]
        at com.twitter.chill.SerDeState.readClassAndObject(SerDeState.java:61) ~[chill-java-0.3.4.jar:0.3.4]
        at com.twitter.chill.KryoPool.fromBytes(KryoPool.java:94) ~[chill-java-0.3.4.jar:0.3.4]
        at com.twitter.chill.KryoInjection$$anonfun$invert$1.apply(KryoInjection.scala:30) ~[chill-bijection_2.10-0.3.4.jar:0.3.4]
        at com.twitter.chill.KryoInjection$$anonfun$invert$1.apply(KryoInjection.scala:30) ~[chill-bijection_2.10-0.3.4.jar:0.3.4]
        at com.twitter.bijection.Inversion$$anonfun$attempt$1.apply(Inversion.scala:30) ~[bijection-core_2.10-0.5.2.jar:na]
        at scala.util.Try$.apply(Try.scala:161) ~[scala-library-2.10.3.jar:0.13.0]
        ... 80 common frames omitted
```

**Comment by georgeOsdDev** [comment]
String message is OK. But big image file become error.
